### ISSUE TITLE
玩转机器学习补充的pandas部分的Data-Indexing-and-Selection有一个描述错误

### ISSUE THREAD

**Issue by a843725157** [liuyubobobo/Play-with-Machine-Learning-Algorithms#1]
![image](https://user-images.githubusercontent.com/24978635/39808376-588dda46-53b1-11e8-9cf0-fdefa64c0874.png)

**Comment by liuyubobobo** [comment]
谢谢你的建议：）

课程未来可能会有所变动，Optional的内容暂时全面下线：）
